#!/usr/bin/env ruby
# frozen_string_literal: true

require 'sscharter'
require 'sscharter/cli'

unless subcommand = Sunniesnow::Charter::CLI.commands[ARGV.shift&.to_sym]
	$stderr.puts "Usage: #{File.basename $0} <#{Sunniesnow::Charter::CLI.commands.keys.join '|'}>"
	exit 1
end

exit subcommand.run || 0
