name: Ruby

on:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    name: Publish to RubyGems
    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - name: Publish
      uses: rubygems/release-gem@v1
